Repository react-native-community/directory, pull requests merged in 2024-07, with the labels that each got.

#1199 Add hidden filter for unmaintained libs
  util/search.js
Labels: New Feature, deploy

#1200 convert New Architecture metadata to compatibility tag
  README.md
  components/CompatibilityTags.tsx
  components/Icons/index.tsx
  components/Library/MetaData.tsx
  components/Library/NewArchitectureTag.tsx
  components/Library/UnmaintainedLabel.tsx
  components/Library/index.tsx
  components/Tag.tsx
  components/Tooltip.tsx
  debug-github-repos.json
Labels: Design, New Feature, deploy

#1201 Support filtering by not supported and untested with new arch
  components/Library/NewArchitectureTag.tsx
  util/newArchStatus.ts
  util/search.js
Labels: New Feature, deploy

#1202 Build script tweaks data update
  react-native-libraries.json
  scripts/check-resources.js
  scripts/fetch-github-data.js
Labels: deploy

#1203 Add newArchitectureNote and alternatives fields, update data and UI
  README.md
  components/Library/NewArchitectureTag.tsx
  components/Library/UnmaintainedLabel.tsx
  components/Library/index.tsx
  debug-github-repos.json
  pages/scoring.tsx
  react-native-libraries.json
  react-native-libraries.schema.json
  types/index.ts
  util/newArchStatus.ts
Labels: New Feature, deploy

#1208 increase stagger time for bulk GH queries
  scripts/build-and-score-data.js
Labels: deploy
